# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae3cdaf5cc4862b3b418a0a9ca46cf7f061af4431713c3a64846c3a13328b7e6ae5d03645d5bd3c1316d84043a8640609f8187bd7b4db9ad83d58ebd42f68f36
  private_api_key: # Insert your private API key here
  public_api_key: # Insert your public API key here

test:
  secret_key_base: d177bdf0f853eb399ddb06bfdfd9e9cd4effd95118b47342168bfba04f294094af6b4d4f6652598c2a74108862948c5f8acf84f3c95af66c4f7bc0245b6fed2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
